version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx_airport
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    links:
      - php
  php:
    image: php:fpm
    volumes:
      - ./app:/app
    command: /bin/sh -c "cd /app/ && composer install"
